---
dist: xenial
sudo: false
# We always want to be able to reach a tagged version in `git describe`
git:
  depth: false
  quiet: true

language: python
python:
- '3.6'
env:
matrix:
  include:
  - env: STABLE_DATACUBE=true
  allow_failures:
  - env: STABLE_DATACUBE=''

addons:
  postgresql: '9.6'
  services:
  - postgresql
  apt:
    packages:
    - cython3
    - gdal-bin
    - gfortran
    - libatlas-base-dev
    - libatlas-dev
    - libgdal1-dev
    - libgdal-dev
    - libhdf5-serial-dev
    - liblapack-dev
    - libnetcdf-dev
    - libproj-dev
    - libudunits2-0
    - libudunits2-dev
    - libxml2-dev
    - libxslt-dev
    - postgresql-9.6-postgis-2.4
    - shellcheck
before_install:
  # Database for the integration tests.
- createdb dea_integration
  # Tests should never use the default datacube config, so add a "honeypot" that fails.
- cp .travis/honeypot.conf ~/.datacube.conf

# Set paths for building python-gdal
- export CPLUS_INCLUDE_PATH=/usr/include/gdal
- export C_INCLUDE_PATH=/usr/include/gdal
- export GDAL_DATA="$(gdal-config --datadir)"
# Install pygdal bindings compatible with dpkg based gdal libs
- pip install 'GDAL==1.11.*'
- cat /etc/postgresql/*/main/postgresql.conf

install:
- travis_retry pip install --upgrade pip pytest pytest-cov
- travis_retry pip install -r requirements-test.txt
- |
  if [ -z "${STABLE_DATACUBE}" ]; then
      echo "Installing latest develop datacube+dea"
      # ? travis_retry pip install git+https://github.com/GeoscienceAustralia/eo-datasets.git
      travis_retry pip install -U --extra-index-url https://packages.dea.gadevs.ga/ 'datacube>=0.0.dev0' 'digitalearthau>=0.0.dev0'
  else
      echo "Using stable datacube+dea"
      # We already installed datacube+dea stable in requirements.txt
      # travis_retry pip install -U --extra-index-url https://packages.dea.gadevs.ga/ 'digitalearthau==20180116+268.g391cbc0'

      # Stable datacube has an issue on alchemy 1.3: https://github.com/opendatacube/datacube-core/pull/680
      travis_retry pip install 'sqlalchemy==1.2.*'
  fi
- pip freeze
- pip install .[test]
- pip freeze

script:
- make lint
- make test

after_success:
- ls -lha
- coveralls

notifications:
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      secure: XuckJxUiZGuprePxfosIwa+Q1MZXo+bsSmBeKGGK0Ep7EBn4GxbLsJ2XZACPqoPRePH5qHseg1FuHtXx1u0AcnEZ9wX9RHd3mx7TiY2fbE8TWN+vjOvfCxU/qraQxmdPrXja7Y7+OFxjhOKtVb6t2jHlQPpaXUq5Xo/L+73+Tr6IQuQctYCjEiJDtYNJqi8akMT29L9qmPWcYPcXyVpj0KMa8Db1YOkgal/OXqi/Uv5ZijXRERejDcudcaKk1pTL2aV/JUqXjaneEQoJL4dGBOYiWbS+Ye27XDyryHT2caFeH5cJ4KFn/T+3X49DtbjIZqR5pACQeKaAWm5iOKMP+GfonQxh6+4GUqgssn6d9/QWs0GsVtJcN/Rbq/kVMjX7anS5pJfUhiV63hfWIYzTXt1cuNXpupuVyOJLUZCcRyyKkFFLBXJcFPQ07UWofxj8ipa+SWvY24411VpvnANGqfuOTj/ZTQrM8SVVuPITjOn8AUX34ZqcHGajIlkcJKl0vEZZOExsdhgeZYRs24CZ4u4/EcGjJy9GgiXim5gBJbzPF7fDWjQ1oyIrLtdSvi2H/zX9vaKhsgbeRiLY6X3xdEq3APCWzswK+d5lzgfRjd9RxDC5yH8a22l4mhcHQQ9XqmC52AcUZv/QDHeN5qyKL07y09xxAwOqlQYmjP5XyVg=
